In [31]:
import numpy as np
import math
import itertools

In [21]:
dim = 3
h = np.random.uniform(0.05,0.4,3)
N_half = np.random.randint(50,125,3)

x_sample = [np.arange(-Ns[ind],Ns[ind]+1)*dx[ind] for ind in range(dim)]
x_grid = np.meshgrid(*x_sample)
x_lin = np.stack([x_grid[ind].reshape(-1) for ind in range(dim)], axis=1)




In [30]:
mesh_to_index = np.arange(x_lin.shape[0]).reshape(x_grid[0].shape)

In [32]:
index_to_mesh = {
    int(mesh_to_index[multi_index]): multi_index for multi_index in itertools.product(
        *[range(axis_len) for axis_len in mesh_to_index.shape])
}

In [ ]:
stencil = []
counter = 0
for sample_index_linear in range(len(index_to_mesh)):
    sample_index_grid = index_to_mesh[sample_index_linear]
    stencil_new = []
    for neighbors in 

In [35]:
mesh_to_index[0,2,154]

np.int64(500)

In [ ]:
index_to_mesh = {int(mesh_to_index[i]): i for i in itertools.product(*[range(j) for j in mesh_to_index.shape])}


In [29]:
mesh_to_index[i]

NameError: name 'i' is not defined

In [28]:
mesh_to_index

array([[[      0,       1,       2, ...,     170,     171,     172],
        [    173,     174,     175, ...,     343,     344,     345],
        [    346,     347,     348, ...,     516,     517,     518],
        ...,
        [  37022,   37023,   37024, ...,   37192,   37193,   37194],
        [  37195,   37196,   37197, ...,   37365,   37366,   37367],
        [  37368,   37369,   37370, ...,   37538,   37539,   37540]],

       [[  37541,   37542,   37543, ...,   37711,   37712,   37713],
        [  37714,   37715,   37716, ...,   37884,   37885,   37886],
        [  37887,   37888,   37889, ...,   38057,   38058,   38059],
        ...,
        [  74563,   74564,   74565, ...,   74733,   74734,   74735],
        [  74736,   74737,   74738, ...,   74906,   74907,   74908],
        [  74909,   74910,   74911, ...,   75079,   75080,   75081]],

       [[  75082,   75083,   75084, ...,   75252,   75253,   75254],
        [  75255,   75256,   75257, ...,   75425,   75426,   75427],
    

In [ ]:
num_neighbors = 3

In [12]:
x_lin

[array([-30.89263492, -30.89263492, -30.89263492, ...,  30.89263492,
         30.89263492,  30.89263492], shape=(5668691,)),
 array([-28.05151867, -28.05151867, -28.05151867, ...,  28.05151867,
         28.05151867,  28.05151867], shape=(5668691,)),
 array([-10.18067119, -10.0622913 ,  -9.9439114 , ...,   9.9439114 ,
         10.0622913 ,  10.18067119], shape=(5668691,))]

In [10]:
X_grid[0].shape

(151, 217, 173)